# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Female',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('profile_picture', models.FileField(default='/media/default_f.jpg', upload_to='')),
                ('premium_user', models.BooleanField(default=False)),
                ('basic_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Male',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('profile_picture', models.FileField(default='media/default_m.gif', upload_to='')),
                ('premium_user', models.BooleanField(default=False)),
                ('basic_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
