# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_female',
            name='profile_picture',
            field=models.FileField(default='/media/default_f.jpg', upload_to='/media'),
        ),
        migrations.AlterField(
            model_name='user_male',
            name='profile_picture',
            field=models.FileField(default='media/default_m.gif', upload_to='/media'),
        ),
    ]
