# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 03:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Login', '0002_auto_20170503_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.BooleanField()),
                ('question2', models.BooleanField()),
                ('question3', models.BooleanField()),
                ('question4', models.BooleanField()),
                ('question5', models.BooleanField()),
                ('basic_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user_female',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_male',
            name='profile_picture',
            field=models.FileField(upload_to=''),
        ),
    ]
