# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20170504_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_responses',
            name='question1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='question_responses',
            name='question2',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='question_responses',
            name='question3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='question_responses',
            name='question4',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='question_responses',
            name='question5',
            field=models.CharField(max_length=3),
        ),
    ]
